<template>
  <svg class="loading" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 531.94 531.94">
    <g id="图层_2" data-name="图层 2">
      <g id="rabbit" class="rabbit jello-horizontal">
        <path
          class="cls-1"
          d="M449.91,363.46c-8.72-5.8-12.53-16-9.41-25.37,21.54-64.88,36-124.31,42.17-176.74,2.74-23.15-2.17-43.39-13.59-55.52-7.2-7.65-16.42-11.65-27.39-11.87-33.45-.66-41.05,26.07-42.76,37.55-.69,4.65-.24,21.34.32,42.46,1,36.64,2.23,86.82-.29,133.16-.66,11.94-11.33,21.14-24.29,21a26.47,26.47,0,0,1-6.72-1A381.54,381.54,0,0,0,266.4,313.78a381.52,381.52,0,0,0-101.54,13.36,26.47,26.47,0,0,1-6.72,1c-13,.17-23.63-9-24.29-21-2.52-46.33-1.26-96.51-.29-133.15.56-21.13,1-37.81.31-42.47C132.17,120,124.57,93.3,91.12,94c-11,.22-20.19,4.22-27.39,11.87C52.31,118,47.4,138.21,50.14,161.35c6.19,52.44,20.63,111.86,42.17,176.74,3.12,9.38-.69,19.57-9.41,25.37-26.89,17.87-46.28,39-57.37,61.69v.4a80.94,80.94,0,0,0,80.86,80.85H478.74a27.69,27.69,0,0,0,27.66-27.66V423.37C495.18,401.36,476.1,380.86,449.91,363.46Zm-271.3,81.47C167.17,455.16,158,435.39,162.78,411c-4.7-24.18,4.61-43.75,16-33.76,11.45-10.23,20.64,9.15,15.83,33.43C199.3,435,190,454.91,178.61,444.93Zm175.78,0c-11.39,10-20.69-10-16-34.22-4.82-24.28,4.38-43.66,15.83-33.43,11.39-10,20.7,9.59,16,33.76C375,435.39,365.83,455.16,354.39,444.93Z"
        />
      </g>
      <g id="frame" class="frame">
        <path
          class="cls-1"
          d="M425.55,0H53.19A53.2,53.2,0,0,0,0,53.19V425.55A106.39,106.39,0,0,0,106.39,531.94H478.74a53.2,53.2,0,0,0,53.2-53.2V106.39A106.39,106.39,0,0,0,425.55,0Zm93.62,478.74a40.48,40.48,0,0,1-40.43,40.43H106.39a93.73,93.73,0,0,1-93.62-93.62V53.19A40.48,40.48,0,0,1,53.19,12.77H425.55a93.73,93.73,0,0,1,93.62,93.62Z"
        />
      </g>
    </g>
  </svg>
</template>

<style lang="less" scoped>
.loading {
  width: 200px;
  height: 200px;
}

.frame{
    overflow: hidden;
    padding:20px;
}

.rabbit {
  transform-origin: 266px 532px;
}

.jello-horizontal {
  -webkit-animation: jello-horizontal 1.5s infinite both;
  animation: jello-horizontal 1.5s infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-5-18 15:11:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}

.cls-1 {
  fill: #333;
}
</style>

<script setup></script>
